production:
  adapter: postgresql
  encoding: unicode
  database: magice_recipe
  pool: 10
  username: postgres
  password: password
  host: localhost
  port: 5432

development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: recipe_development
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: recipe_test
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432