# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c8fd9f1da5090c3ff70ed46d513d91083a717dca4c9196fa7b9688e547ffa6cc292e2402bcfa9279df6fd6c8be5ce12861f7466b363efe2c933422a4e6abf2f

test:
  secret_key_base: 78b173b2e13cec4f04bb349333257d7996dd9755ee4b38e0a67074e0f6a4a8bbfef6e40e609de21a00b938207390f4bc274b68fa64a59b7784773ffc8034d81c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
